'use client'

import { useRef } from 'react'
import { useServerInsertedHTML } from 'next/navigation'

interface StyleProviderProps {
  children: React.ReactNode
}
export function StyleProvider(StyleProvider: StyleProviderProps) {
  const inserted = useRef(false)
  useServerInsertedHTML(() => {
    const styleText = `html,body{ height: 100%;}`

    if (inserted.current)
      return null

    inserted.current = true

    return (
      <style
        id="global-style"
                // to make sure this style is inserted before Ant Design's style generated by client
        data-rc-order="prepend"
        data-rc-priority="-1000"
        dangerouslySetInnerHTML={{ __html: styleText }}
      />
    )
  })

  return (
    <>
      {StyleProvider.children}
    </>
  )
}
