name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Build Docker image
        run: |
          docker image build -t kkpages .
          docker login -u ${ALIYUN_DOCKER_USERNAME} -p ${ALIYUN_DOCKER_PASSWORD} registry.cn-beijing.aliyuncs.com
          docker tag kkpages registry.cn-beijing.aliyuncs.com/xk-repo/kkpages:latest
          docker push registry.cn-beijing.aliyuncs.com/xk-repo/kkpages:latest
        env:
          ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 0
